baseURL = "https://anil.battalahalli.me"
languageCode = "en-us"
title = "Chaos"
theme = [ "PaperMod" ]

[markup.goldmark.renderer]
unsafe = true

[params.profileMode]
enabled = true
title = "Anil Battalahalli"
subtitle = "My name is Anil Battalahalli ([**ಅನಿಲ ಬಟ್ಟಲಹಳ್ಳಿ**](https://en.wikipedia.org/wiki/Kannada)) and this is the stuff that I do to amount to entropy. [More about me **here**](/about/)."
imageUrl = "home/chaotic_swirls.gif"
imageWidth = 220
imageHeight = 220

[[params.socialIcons]]
name = "email"
url = "mailto:anilbs@umich.edu"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/abattalahalli/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/AnilBattalahalli"

[[menu.main]]
name = "About Me"
url = "/about/"
weight = 30

[[menu.main]]
name = "Statistics"
url = "/statistics/"
weight = 10

# [[menu.main]]
# name = "Self Study"
# url = "/selfstudy/"
# weight = 12

[[menu.main]]
name = "Kannada"
url = "/kannada/"
weight = 20

[[menu.main]]
name = "Film Photography"
url = "https://www.lomography.com/homes/anilbattalahalli"
weight = 15
